language: cpp
compiler:
  - clang
notifications:
  email: false
env:
  matrix:
    - JULIAVERSION="juliareleases"
before_install:
    - sudo add-apt-repository ppa:staticfloat/julia-deps -y
    - sudo add-apt-repository ppa:staticfloat/${JULIAVERSION} -y
    - sudo apt-get update -qq -y
    - sudo apt-get install gfortran libpcre3-dev julia -y
    - git config --global user.name "Travis User"
    - git config --global user.email "travis@example.net"
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
script:
    - julia -e 'Pkg.init()'
    - julia -e 'Pkg.clone("https://github.com/gragusa/Divergences.jl.git")'
    - julia -e 'Pkg.clone("https://github.com/gragusa/Divergences.jl.git")'
    - julia -e 'Pkg.clone("https://github.com/gragusa/ModelsGenerators.git")'
    - julia -e 'Pkg.test("MinimumDivergence", coverage=true)'
after_success:
    - julia -e 'cd(Pkg.dir("MinimumDivergence")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'

